CON-3619 Migrated the view changes page from commitments v1 to v2
SkillsFundingAgency/das-providercommitments pull request #220
Opened 2021-06-29 12:54 UTC by ChrisJWoodcock

2021-06-30 09:58 UTC, cofaulco commented on src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/DependencyResolution/IoC.cs
> +            registry.IncludeRegistry<LocalDevRegistry>();
does this need to be commented out ?

2021-06-30 09:59 UTC, cofaulco requested changes
1 thing to address

2021-06-30 10:44 UTC, cofaulco approved these changes

2021-06-30 12:01 UTC, cofaulco approved these changes

2021-07-01 07:59 UTC, ChrisJWoodcock commented on src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/DependencyResolution/IoC.cs
> +            registry.IncludeRegistry<LocalDevRegistry>();
Updated comment and commented out line

2021-07-05 08:07 UTC, merged