Cs 665 add email address to details view
SkillsFundingAgency/das-providercommitments pull request #222
Opened 2021-06-30 16:47 UTC by Chazzysb

CS-665 this change adds the email row to the apprentice details view page

2021-07-01 07:38 UTC, Pauljgraham requested changes
Looks good, but I think we both missed a small point on this story and the previous one you did the day before yesterday, about not displaying the line if no email address

2021-07-01 07:38 UTC, Pauljgraham commented on src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Apprentice/Details.cshtml
> +                <td id="apprentice-email" class="govuk-table__cell das-table-cell-width-55">@Model.Email</td>
Couple of points I double checked on the story.

1. Label should be 'Email address' I think
2. The AT on the story says only display this line if the email address is not null

2021-07-01 08:52 UTC, Pauljgraham approved these changes

2021-07-01 10:41 UTC, Pauljgraham approved these changes

2021-07-07 12:58 UTC, hkf-tech approved these changes

2021-07-12 21:37 UTC, merged