Qt1-386 RPL initial validation file upload file
SkillsFundingAgency/das-providercommitments pull request #528
Opened 2023-07-12 07:47 UTC by alireid

2023-07-12 12:35 UTC, Pauljgraham requested changes
Looks good a few really minor points

2023-07-12 12:35 UTC, Pauljgraham commented on src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.UnitTests/Queries/GetBulkUploadValidationErrors/BulkUploadValidateDataHandlerTests.cs
> +                BulkUploadValidateDataHandler = new FileUploadValidateDataHandler(_outerApiService.Object, _modelMapper.Object, _bulkUploadParser.Object, _authorizationService.Object);
This is a tiny bit picky (as the existing tests aren't great), but we have added this new property but I can't see if we test that this is set correctly when passing it to the ValidateBulkUploadRequest()

2023-07-12 13:40 UTC, alireid commented on src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments/Infrastructure/OuterApi/Requests/PostValidateBulkUploadDataRequest.cs
> +
completed, thanks

2023-07-19 07:59 UTC, Pauljgraham submitted a review, later dismissed

2023-07-19 08:01 UTC, closed without merging