Qt1-440 create first file upload log
SkillsFundingAgency/das-providercommitments pull request #542
Opened 2023-08-25 11:57 UTC by Pauljgraham

2023-08-25 12:12 UTC, alireid requested changes

2023-08-25 12:12 UTC, alireid commented on src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments/Queries/BulkUploadValidate/FileUploadValidateDataResponse.cs
> +        public long FileUploadLogId { get; set; }
@Pauljgraham please change to LogId

2023-08-29 08:11 UTC, Pauljgraham commented on src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments/Queries/BulkUploadValidate/FileUploadValidateDataResponse.cs
> +        public long FileUploadLogId { get; set; }
done

2023-08-29 08:12 UTC, Pauljgraham commented on src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments/Queries/BulkUploadValidate/FileUploadValidateDataResponse.cs
> +        public long FileUploadLogId { get; set; }
done

2023-08-29 08:46 UTC, alireid approved these changes

2023-09-12 10:40 UTC, closed without merging